# -----------------------------
# 01 - Doctor Service
# -----------------------------
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: doctor-service
  labels:
    app: healthcare-system
    service: doctor
spec:
  replicas: 2
  selector:
    service: doctor
  template:
    metadata:
      labels:
        service: doctor
    spec:
      containers:
        - name: doctor-service
          image: doctor-service:latest
          ports:
            - name: http
              containerPort: 8002
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: doctor-service
spec:
  selector:
    service: doctor
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      protocol: TCP
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: doctor-service
spec:
  to:
    kind: Service
    name: doctor-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

# -----------------------------
# 02 - Appointment Service
# -----------------------------
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: appointment-service
  labels:
    app: healthcare-system
    service: appointment
spec:
  replicas: 2
  selector:
    service: appointment
  template:
    metadata:
      labels:
        service: appointment
    spec:
      containers:
        - name: appointment-service
          image: appointment-service:latest
          ports:
            - name: http
              containerPort: 8003
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
            - secretRef:
                name: healthcare-db-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  selector:
    service: appointment
  ports:
    - name: http
      port: 8003
      targetPort: 8003
      protocol: TCP
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: appointment-service
spec:
  to:
    kind: Service
    name: appointment-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

# -----------------------------
# 03 - Medical Records Service
# -----------------------------
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: medical-records-service
  labels:
    app: healthcare-system
    service: medical-records
spec:
  replicas: 2
  selector:
    service: medical-records
  template:
    metadata:
      labels:
        service: medical-records
    spec:
      containers:
        - name: medical-records-service
          image: medical-records-service:latest
          ports:
            - name: http
              containerPort: 8004
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
            - secretRef:
                name: healthcare-db-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: medical-records-service
spec:
  selector:
    service: medical-records
  ports:
    - name: http
      port: 8004
      targetPort: 8004
      protocol: TCP
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: medical-records-service
spec:
  to:
    kind: Service
    name: medical-records-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

# -----------------------------
# 04 - Billing Service
# -----------------------------
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: billing-service
  labels:
    app: healthcare-system
    service: billing
spec:
  replicas: 2
  selector:
    service: billing
  template:
    metadata:
      labels:
        service: billing
    spec:
      containers:
        - name: billing-service
          image: billing-service:latest
          ports:
            - name: http
              containerPort: 8006
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
            - secretRef:
                name: healthcare-db-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 8006
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8006
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: billing-service
spec:
  selector:
    service: billing
  ports:
    - name: http
      port: 8006
      targetPort: 8006
      protocol: TCP
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: billing-service
spec:
  to:
    kind: Service
    name: billing-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
