# 01 - Auth DeploymentConfig
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: auth-service
  labels:
    app: healthcare-system
    service: auth
spec:
  replicas: 2
  selector:
    app: healthcare-system
    service: auth
  template:
    metadata:
      labels:
        app: healthcare-system
        service: auth
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          ports:
            - name: http
              containerPort: 8000
          # Use ConfigMap + Secret for environment variables
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
            - secretRef:
                name: healthcare-db-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"

---
# 02 - Auth Service
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: healthcare-system
    service: auth
spec:
  selector:
    app: healthcare-system
    service: auth
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP

---
# 03 - Auth Route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: auth-service
  labels:
    app: healthcare-system
    service: auth
spec:
  to:
    kind: Service
    name: auth-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
