
# Auth Service
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: auth-service
  labels:
    app: healthcare-system
    service: auth
spec:
  replicas: 2
  selector:
    app: healthcare-system
    service: auth
  template:
    metadata:
      labels:
        app: healthcare-system
        service: auth
    spec:
      containers:
      - name: auth-service
        image: auth-service:latest
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        - name: DB_HOST
          value: "healthcare-db"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "healthcare"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: healthcare-db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: healthcare-db-secret
              key: password
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: healthcare-system
    service: auth
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: healthcare-system
    service: auth
  type: ClusterIP
---
apiVersion: v1
kind: Route
metadata:
  name: auth-service
  labels:
    app: healthcare-system
    service: auth
spec:
  to:
    kind: Service
    name: auth-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect