# 01 - Patient DeploymentConfig
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: patient-service
  labels:
    app: healthcare-system
    service: patient
spec:
  replicas: 2
  selector:
    app: healthcare-system
    service: patient
  template:
    metadata:
      labels:
        app: healthcare-system
        service: patient
    spec:
      containers:
        - name: patient-service
          image: patient-service:latest
          ports:
            - name: http
              containerPort: 8001
          # Use ConfigMap + Secret for env
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: healthcare-db-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"

---
# 02 - Patient Service
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  labels:
    app: healthcare-system
    service: patient
spec:
  selector:
    app: healthcare-system
    service: patient
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP
  type: ClusterIP

---
# 03 - Patient Route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: patient-service
  labels:
    app: healthcare-system
    service: patient
spec:
  to:
    kind: Service
    name: patient-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
