# 01 - Database Secret
apiVersion: v1
kind: Secret
metadata:
  name: healthcare-db-secret
type: Opaque
stringData:
  username: healthcare_user
  password: supersecurepassword

---
# 02 - PersistentVolumeClaim for Postgres
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# 03 - PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-db
  labels:
    app: healthcare-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-db
  template:
    metadata:
      labels:
        app: healthcare-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: healthcare-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: healthcare-db-secret
                  key: password
            - name: POSTGRES_DB
              value: healthcare
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc

---
# 04 - PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: healthcare-db
  labels:
    app: healthcare-db
spec:
  selector:
    app: healthcare-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
